//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public int Id { get; set; }
        public string EventTitle { get; set; }
        public string Abstract { get; set; }
        public string EventDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Location { get; set; }
        public string Url { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string EventGroupTitle { get; set; }
        public string EventGroupName { get; set; }
        public string EventTypeOne { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastUpdateDateTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
